CITIES = {
    "Jabodetabek": [
        "Jakarta, Indonesia",
        "Bogor",
        "Depok",
        "Tangerang",
        "South Tangerang",
        "Bekasi",
    ],
    "Bandung": ["Bandung, Indonesia"],
    "Bali": ["Bali, Indonesia"],
    "Surabaya": ["Surabaya, Indonesia"],
    "Makassar": ["Makassar, Indonesia"],
    "Singapore": ["Singapore"],
    "Bengaluru": ["Bengaluru, India"],
    "Tirana": ["Tirana, Albania"],
    "Yerevan": ["Yerevan, Armenia"],
    "Minsk": ["Minsk, Belarus"],
    "Brussels": ["Brussels, Belgium"],
    "Sarajevo": ["Sarajevo, Bosnia and Herzegovina"],
    "Sofia": ["Sofia, Bulgaria"],
    "Zagreb": ["Zagreb, Croatia"],
    "Nicosia": ["Nicosia, Cyprus"],
    "Prague": ["Prague, Czech Republic"],
    "Tallinn": ["Tallinn, Estonia"],
    "Helsinki": ["Helsinki, Finland"],
    "Paris": ["Paris, France"],
    "Tbilisi": ["Tbilisi, Georgia"],
    "Berlin": ["Berlin, Germany"],
    "Budapest": ["Budapest, Hungary"],
    "Reykjavik": ["Reykjavík, Iceland"],
    "Dublin": ["Dublin, Ireland"],
    "Rome": ["Rome, Italy"],
    "Nur-Sultan": ["Nur-Sultan, Kazakhstan"],
    "Riga": ["Riga, Latvia"],
    "Vilnius": ["Vilnius, Lithuania"],
    "Luxembourg": ["Luxembourg City, Luxembourg"],
    "Chisinau": ["Chișinău, Moldova"],
    "Podgorica": ["Podgorica, Montenegro"],
    "Amsterdam": ["Amsterdam, Netherlands"],
    "Skopje": ["Skopje, North Macedonia"],
    "Oslo": ["Oslo, Norway"],
    "Lisbon": ["Lisbon, Portugal"],
    "Bucharest": ["Bucharest, Romania"],
    "Belgrade": ["Belgrade, Serbia"],
    "Bratislava": ["Bratislava, Slovakia"],
    "Ljubljana": ["Ljubljana, Slovenia"],
    "Madrid": ["Madrid, Spain"],
    "Stockholm": ["Stockholm, Sweden"],
    "Bern": ["Bern, Switzerland"],
    "Ankara": ["Ankara, Turkey"],
    "New_York_City": ["New York City, USA"],
    "Chicago": ["Chicago, USA"],
    "Los_Angeles": ["Los Angeles, USA"],
    "San_Francisco": ["San Francisco, USA"],
    "Philadelphia": ["Philadelphia, USA"],
}

TOP_LEVEL_OSM_TAGS = [
    "aerialway",
    "aeroway",
    "amenity",
    "barrier",
    "boundary",
    "building",
    "craft",
    "emergency",
    "geological",
    "healthcare",
    "highway",
    "historic",
    "landuse",
    "leisure",
    "man_made",
    "military",
    "natural",
    "office",
    "place",
    "power",
    "public_transport",
    "railway",
    "route",
    "shop",
    "sport",
    "telecom",
    "tourism",
    "water",
    "waterway",
]

SELECTED_TAGS = [
    "aeroway",
    "amenity",
    "building",
    "healthcare",
    "historic",
    "landuse",
    "leisure",
    "military",
    "natural",
    "office",
    "shop",
    "sport",
    "tourism",
    "water",
    "waterway",
]

KEY_VALUES_TO_DROP = {
    "natural": [
        "tree",
        "tree_row",
        "valley",
        "scrub",
        "heath",
        "moor",
        "grassland",
        "fell",
        "bare_rock",
        "scree",
        "shingle",
        "sand",
        "wetland",
        "glacier",
        "reef",
        "spring",
        "hot_spring",
        "geyser",
        "peak",
        "volcano",
        "peninsula",
        "isthmus",
        "ridge",
        "arete",
        "cliff",
        "saddle",
        "dune",
        "rock",
        "stone",
        "sinkhole",
        "cave_entrance",
    ],
    "amenity": [
        "bench",
        "grit_bin",
        "parking_space",
        "post_box",
        "sanitary_dump_station",
        "recycling",
        "waste_basket",
        "waste_disposal",
        "waste_transfer_station",
    ],
    "landuse": ["grass"],
}
